- flixel/addons/ui/FlxUI.hx
Sprites with a src tag weren't resized with a exact_size tag, like this:
```	
<sprite src="ui/title_back" color="0x48AF1D" x="0" y="0">
<exact_size height="stretch:top,bottom" width="stretch:left,right" />
</sprite>
```
> Moved one block up in _loadSprite, to support exact_size for sprites with a src-tag

- README.md
Overriding the function signature from the original readme will result in a compiler error because it missed the params array.
> Fixed function signature for getEvent()

- flixel/addons/ui/FlxUIDropDownMenu.hx
Destroying a dropdown twice caused an error since list was null.
> Fix for destroying dropdowns

- flixel/addons/ui/FlxUITypedButton.hx
FlxUITypedButton<T:FlxSprite> should declare it implements IFlxUIButton. For example this is needed to use this type of button in a FlxUIList.
> "implements IFlxUIButton" in FlxUITypedButton.hx

- flixel/addons/ui/FlxUI.hx
This helps keep the GC from leaving XML layouts in memory
> Unparent XML references

- flixel/addons/ui/FlxUI.hx
There were some subtle, but major bugs in layout logic. Essentially, the post-load step was not properly recalculating the x,y,width, and height values of objects which were using "pt" values unless you were using `<anchor>`, `<min_size>`, `<max_size>`, or `<exact_size>` tags. (IE, the values set by plain ol' `x,w,width,height` weren't being properly resolved).
This ONLY applied to the post-load step. 
(Basically, Flixel-UI loads positions and sizes twice, in order to let you set object's width and height relative to other objects without having to be overly concerned with the order in which you define your objects in the layout code. The initial loading logic is correct, it's only the post-loading logic that was incorrect, and only in certain circumstances).
I'm hoping this doesn't …
> Fix layout logic

- flixel/addons/ui/FlxInputText.hx
FlxInputText is not working on cpp as of OpenFL 3.4.0 and Lime 2.7.0. The first time the text is set works, but subsequent calls to `set_text` will not change the text the user sees.
This small change makes FlxInputText works again on cpp target. Also tested on Flash and HTML5, both working too.
> FlxInputText: fix for last versions of Lime/OpenFL

- flixel/addons/ui/FlxUICursor.hx
I'm not really sure it's a proper fix to #160, but it works for my game at the very least. 
I noticed that if I never moved the mouse... the cursor worked fine with the keyboard. The problem was that _jumpToXY was setting location to -1 whenever the mouse moved but there was no control to focus and then when you pressed a key on the keyboard _findNextY tried to index the control array by location (-1), crashing the app of course.
> Fixed cursor crash, closes #160

- flixel/addons/ui/FlxUISubState.hx
This just adds a createUI method to FlxUISubState the same as exists in FlxUIState - which allows you to use a subclass of FlxUI.
> add createUI to FlxUISubState to match FlxUIState

- flixel/addons/ui/FlxUIButton.hx
Adding icon to button will now take into account label offsets (IF they are defined before calling `addIcon`)
> addIcon use labelOffsets

- flixel/addons/ui/FlxUITooltipManager.hx
If you are using some custom cameras that would normally appear in front of your tooltips, this allows you enough control to fix them so they're not longer hidden, just like with any FlxSprite.  Fixes #183.
> Add a function so you can set tooltip cameras

- README.md
I noticed that the <9slicesprite> tag wasn't being handled by FlxUI. FlxUI_loadThing missed the tag but had other variations listed:
case "chrome", "nineslicesprite", "nine_slice_sprite", "nineslice", "nine_slice": return _load9SliceSprite(info);
I replaced the missing tag with the second entry from that list.
> Wrong <9slicesprite> tag

- flixel/addons/ui/FlxUI.hx
See [issue #211](https://github.com/HaxeFlixel/flixel-ui/issues/211).
> Fix for wrong path on <sprite> src, closes #211

- flixel/addons/ui/FlxUICursor.hx
The UI cursor would not properly scroll with fixed UI elements, instead staying at the initialization position. There's also a redundant FLX_MOUSE check. Fixes #229
> Fix FlxUICursor camera scroll

- flixel/addons/ui/FlxInputText.hx
Add support for desktop and HTML5 javascript paste events by adding an event handler that fills the field as the parent text element changes. Fixes an issue with maxLength text entry. Closes #251.
> Add paste support for desktop and web + fix maxLength input

- flixel/addons/ui/FlxUIList.hx
Fixes `prevButton` and `nextButton` not being destroyed if they're not added inside `FlxUIList`.
This also makes the button offset points put back to the pool using `FlxDestroyUtil`, preventing a crash if they're both already null.
> Properly destroy `FlxUIList`

- flixel/addons/ui/FlxUI9SliceSprite.hx
`[] == []` is `false`, because arrays
i simply changed `_slice9 == []` to `_slice9.length != 4` (in FlxUI9SliceSprite, line 161) which would achieve the intended purpose, i think
> fix _slice9 == []

- flixel/addons/ui/FlxInputText.hx
Enables basic soft keyboard functionality for mobile (tested on Android and iOS), adds the ability to automatically deactivate and dismiss fields when Enter is pressed and removes unnecessary variables. Closes #70.
> FlxInputText improvements

- README.md
I was eventually able to figure out how custom widgets work by reading the source code and checking out the demo, but I think it makes sense to include explicit documentation on how to implement custom UI widgets by adding them as tags to the XML.
I made a patch for this but forgot to submit it as a PR.
> Revise documentation to include custom widgets

- flixel/addons/ui/FlxUICursor.hx
> Uicursor flags

- flixel/addons/ui/FlxUICursor.hx
The button width / height always return the center values of the native button. At larger scale modes, the disparity grows enough that other buttons can sometimes be pressed when overlapping each other because it doesn't return the actual center coordinates.
> Return scaled center coordinates for widgets

- flixel/addons/ui/FlxMultiGamepad.hx
- flixel/addons/ui/FlxUICursor.hx
FlxUICursor is oddly written, when there's no gamepads it adds gamepad listeners with a null gamepad, then checks for null gamepads every frame for dozens of inputs. this change will simply not add useless button listeners unless theres a connected gamepad. It also checks whether the current gamepad is disconnected, and removes listeners when that gamepad is disconnected, fixing https://github.com/HaxeFlixel/flixel/pull/2991
@DigiEggz please try this out, or lmk if you don't have time
> FlxUICursor: prevent/remove references to disconnected gamepads

- flixel/addons/ui/FlxUIDropDownMenu.hx
FIxes https://github.com/HaxeFlixel/flixel-ui/issues/274
clicking a dropdown items seemed to first trigger a collapse before it would have selected the item you clicked
Fix proposed by @gamerbross
> prevent premature closing when selecting items

- flixel/addons/ui/FlxInputText.hx
fix for https://github.com/HaxeFlixel/flixel/pull/3236
Will account for SHADOW_XY in a future PR
> temp fix for shadow_xy branch

- flixel/addons/ui/FlxInputText.hx
Fixes https://github.com/HaxeFlixel/flixel-ui/issues/283
> prevent using destroyed graphic on (legacy) FlxInputText

- README.md
This is about the docs of FlxUICheckBox in the readme file:
- the descriptions for the arguments `check_src` and `box_src` were swapped;
- the click event was reported as `click_checkbox` but it really is `click_check_box`: https://github.com/HaxeFlixel/flixel-ui/blob/2756177af4bb74d793406652165ba32702aed489/flixel/addons/ui/FlxUICheckBox.hx#L41
- the params of the `click_check_box` event was described as a single string in the form `checked:true` while it really is an object of type `{name:String, value:Bool}` (an `FlxUI.NamedBool`): https://github.com/HaxeFlixel/flixel-ui/blob/2756177af4bb74d793406652165ba32702aed489/flixel/addons/ui/FlxUICheckBox.hx#L57
> Update README.md: fixed docs of FlxUICheckBox

- flixel/addons/ui/FlxInputText.hx
- flixel/addons/ui/FlxUIGroup.hx
- flixel/addons/ui/FlxUITypedButton.hx
- flixel/addons/ui/FontDef.hx
- flixel/addons/ui/FontFixer.hx
- flixel/addons/ui/U.hx
backwards compatible
For https://github.com/HaxeFlixel/flixel/pull/3340
status animations isn't needed now that status.toString() exists, and it was a weird system to begin with
> Remove refs to statusAnimations for flixel > 5.9
